CREATE TABLE images
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(100) NOT NULL,
    filename     VARCHAR(255),
    data         BYTEA        NOT NULL,
    owner_id     BIGINT       NOT NULL,
    uploaded_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    version      BIGINT       NOT NULL DEFAULT 0
);