CREATE TABLE associations
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(128),
    logo    BIGINT REFERENCES images,
    version BIGINT,
    CONSTRAINT pk_associations PRIMARY KEY (id)
);